import { StaffMember } from './types';

export const staffMembers: StaffMember[] = [
  // ─── TEACHING STAFF: ELEMENTARY ───
  {
    id: 1,
    name: 'Ma. Teresa R. Santos',
    role: 'Grade 6 Adviser / Science Coordinator',
    department: 'Elementary',
    staffType: 'teaching',
    img: 'https://images.unsplash.com/photo-1609126385558-bc3fc5082b0a?auto=format&fit=crop&q=80&w=600',
    bio: 'Ms. Santos has been shaping young minds at MMPNS for over 15 years. Known for her innovative hands-on science experiments, she has led multiple students to regional science fair victories. Her classroom is a laboratory of curiosity where every child is encouraged to question, explore, and discover.',
    education: 'B.S. Elementary Education, Major in General Science — Philippine Normal University',
    yearsAtMmpns: 15,
    specialization: 'Science & Environmental Studies',
    motto: 'Every child is a scientist waiting to be awakened.',
  },
  {
    id: 2,
    name: 'Anna Liza M. Cruz',
    role: 'Grade 3 Adviser / English Coordinator',
    department: 'Elementary',
    staffType: 'teaching',
    img: 'https://images.unsplash.com/photo-1657830633860-bf085e1603d1?auto=format&fit=crop&q=80&w=600',
    bio: 'Ms. Cruz is passionate about building a love for reading in every student. She runs the school\'s Storytelling Club and organizes the annual Literacy Week, turning the entire campus into a book-themed wonderland. Her warm approach makes even the shyest students find their voice.',
    education: 'B.E.Ed., Major in English — University of Santo Tomas',
    yearsAtMmpns: 8,
    specialization: 'Language Arts & Creative Writing',
    motto: 'A book can take you anywhere — even home.',
  },
  {
    id: 3,
    name: 'Ricardo B. Villanueva',
    role: 'Grade 5 Adviser / Math Coordinator',
    department: 'Elementary',
    staffType: 'teaching',
    img: 'https://images.unsplash.com/photo-1701463387028-3947648f1337?auto=format&fit=crop&q=80&w=600',
    bio: 'Mr. Villanueva transforms math anxiety into math excitement. His game-based learning approach and "Math Olympiad" training sessions have produced consistent division-level winners. Students appreciate his patience and his ability to make complex concepts feel simple.',
    education: 'B.S.E., Major in Mathematics — De La Salle University',
    yearsAtMmpns: 11,
    specialization: 'Mathematics & Logical Reasoning',
    motto: 'Numbers tell stories too — you just have to listen.',
  },
  {
    id: 4,
    name: 'Rosario D. Aquino',
    role: 'Grade 1 Adviser / Values Education',
    department: 'Elementary',
    staffType: 'teaching',
    img: 'https://images.unsplash.com/photo-1706295330178-63b3794ad97e?auto=format&fit=crop&q=80&w=600',
    bio: 'Ma\'am Rosario is the first friendly face many MMPNS students encounter as they begin their school journey. With a gentle spirit and deep faith, she integrates values formation into every lesson, ensuring students grow not just academically, but as compassionate human beings.',
    education: 'B.E.Ed., Major in Early Childhood Education — Miriam College',
    yearsAtMmpns: 20,
    specialization: 'Values Formation & Early Literacy',
    motto: 'Plant the seed of kindness early, and it will grow forever.',
  },

  // ─── TEACHING STAFF: JUNIOR HIGH SCHOOL ───
  {
    id: 5,
    name: 'Jonathan P. Reyes',
    role: 'Grade 9 Adviser / Science Department Head',
    department: 'Junior High School',
    staffType: 'teaching',
    img: 'https://images.unsplash.com/photo-1716041040048-228dbae7b6ba?auto=format&fit=crop&q=80&w=600',
    bio: 'Sir JP, as students fondly call him, is the driving force behind MMPNS\'s award-winning science department. His lab demonstrations are legendary — from erupting volcanoes to extracting DNA. He mentors the school\'s research team and has published student papers in youth science journals.',
    education: 'M.S. Biology — Ateneo de Manila University',
    yearsAtMmpns: 12,
    specialization: 'Biology & Research Methodology',
    motto: 'Science is not a subject — it\'s a way of thinking.',
  },
  {
    id: 6,
    name: 'Christine Joy L. Fernandez',
    role: 'Grade 8 Adviser / Filipino Coordinator',
    department: 'Junior High School',
    staffType: 'teaching',
    img: 'https://images.unsplash.com/photo-1740153204601-b2baf50a3f46?auto=format&fit=crop&q=80&w=600',
    bio: 'Ma\'am CJ is a champion of Filipino language and culture. She directs the school\'s Buwan ng Wika celebrations, coaches the declamation team, and runs a creative writing workshop in Filipino. Her dramatic readings of Noli Me Tangere have become a beloved school tradition.',
    education: 'B.S.E., Major in Filipino — University of the Philippines Diliman',
    yearsAtMmpns: 9,
    specialization: 'Filipino Literature & Communication Arts',
    motto: 'Ang wika ay daluyan ng kultura at pagkakakilanlan.',
  },
  {
    id: 7,
    name: 'Mark Anthony G. Dela Cruz',
    role: 'MAPEH Coordinator / Sports Director',
    department: 'Junior High School',
    staffType: 'teaching',
    img: 'https://images.unsplash.com/photo-1752118464988-2914fb27d0f0?auto=format&fit=crop&q=80&w=600',
    bio: 'Coach Mark is the energy behind MMPNS\'s sports programs. A former varsity athlete himself, he has built competitive basketball, volleyball, and athletics teams from the ground up. Beyond sports, he teaches students about discipline, teamwork, and the importance of physical wellness.',
    education: 'B.S. Physical Education — Polytechnic University of the Philippines',
    yearsAtMmpns: 7,
    specialization: 'Physical Education & Athletic Training',
    motto: 'Champions are made in practice, not on game day.',
  },
  {
    id: 8,
    name: 'Maria Fe S. Bautista',
    role: 'Grade 10 Adviser / TLE Coordinator',
    department: 'Junior High School',
    staffType: 'teaching',
    img: 'https://images.unsplash.com/photo-1744956581253-abfd023141b1?auto=format&fit=crop&q=80&w=600',
    bio: 'Ma\'am Fe bridges the gap between academics and real-world skills. Her TLE classes cover everything from basic cookery to entrepreneurship, giving students practical life skills. She organizes the annual "Young Entrepreneurs Fair" where students showcase their own small business ideas.',
    education: 'B.S.E., Major in Technology & Livelihood Education — TUP Manila',
    yearsAtMmpns: 6,
    specialization: 'Entrepreneurship & Home Economics',
    motto: 'Education must prepare students for life, not just exams.',
  },

  // ─── NON-TEACHING STAFF: ACCOUNTING ───
  {
    id: 9,
    name: 'Roberto C. Manalo',
    role: 'Chief Accountant',
    department: 'Accounting',
    staffType: 'non-teaching',
    img: 'https://images.unsplash.com/photo-1646579219100-06ce3ae6302b?auto=format&fit=crop&q=80&w=600',
    bio: 'Mr. Manalo ensures the financial health of MMPNS with precision and integrity. He oversees all accounting operations, from tuition management to budget planning. Parents appreciate his approachable nature and willingness to help families navigate payment arrangements.',
    education: 'B.S. Accountancy — Far Eastern University',
    yearsAtMmpns: 14,
    motto: 'Stewardship is service in numbers.',
  },
  {
    id: 15,
    name: 'Lourdes V. Mendoza',
    role: 'Billing & Collections Officer',
    department: 'Accounting',
    staffType: 'non-teaching',
    img: 'https://images.unsplash.com/photo-1762522921456-cdfe882d36c3?auto=format&fit=crop&q=80&w=600',
    bio: 'Ms. Mendoza handles all tuition billing, payment tracking, and collections with a gentle but organized approach. She works closely with parents to set up installment plans and ensures every account is properly documented. Her friendly demeanor makes even the most stressful financial conversations feel manageable.',
    education: 'B.S. Business Administration, Major in Financial Management — Polytechnic University of the Philippines',
    yearsAtMmpns: 9,
    motto: 'Transparency builds trust.',
  },
  {
    id: 16,
    name: 'Dennis A. Reyes',
    role: 'Payroll & Budget Assistant',
    department: 'Accounting',
    staffType: 'non-teaching',
    img: 'https://images.unsplash.com/photo-1737574821698-862e77f044c1?auto=format&fit=crop&q=80&w=600',
    bio: 'Dennis manages payroll processing for all MMPNS employees and assists with annual budget preparation. He is meticulous with numbers and ensures every peso is accounted for. He also handles government remittances and tax filings, keeping the school compliant with all regulatory requirements.',
    education: 'B.S. Accountancy — University of the East',
    yearsAtMmpns: 5,
    motto: 'Accuracy is the foundation of accountability.',
  },

  // ─── NON-TEACHING STAFF: GUIDANCE ───
  {
    id: 10,
    name: 'Elena R. Pascual',
    role: 'Head Guidance Counselor',
    department: 'Guidance',
    staffType: 'non-teaching',
    img: 'https://images.unsplash.com/photo-1740153204804-200310378f2f?auto=format&fit=crop&q=80&w=600',
    bio: 'Ms. Pascual is the heart of student welfare at MMPNS. She provides individual and group counseling, runs mental health awareness programs, and coordinates with parents on student development. Her door is always open, and generations of students credit her with helping them through tough times.',
    education: 'M.A. Guidance & Counseling — Ateneo de Manila University',
    yearsAtMmpns: 18,
    specialization: 'Adolescent Psychology & Career Counseling',
    motto: 'Every student deserves to be heard.',
  },
  {
    id: 17,
    name: 'Carlo M. Jimenez',
    role: 'Guidance Associate / Career Counselor',
    department: 'Guidance',
    staffType: 'non-teaching',
    img: 'https://images.unsplash.com/photo-1646579886135-068c73800308?auto=format&fit=crop&q=80&w=600',
    bio: 'Mr. Jimenez specializes in career guidance and helps graduating students explore post-secondary pathways. He coordinates career talks, aptitude testing, and college application workshops. His relatable personality makes him a trusted confidant among junior high school students navigating adolescence.',
    education: 'M.A. Psychology — De La Salle University',
    yearsAtMmpns: 4,
    specialization: 'Career Development & Psychometrics',
    motto: 'Know yourself, and the path becomes clear.',
  },
  {
    id: 18,
    name: 'Marissa B. Tanedo',
    role: 'Student Welfare Coordinator',
    department: 'Guidance',
    staffType: 'non-teaching',
    img: 'https://images.unsplash.com/photo-1718006915613-bcb972cabdb1?auto=format&fit=crop&q=80&w=600',
    bio: 'Ms. Tanedo focuses on student behavioral support and coordinates the school\'s anti-bullying programs. She facilitates peer mediation sessions and works with homeroom advisers to identify students who may need additional emotional support. Her warmth and patience create a safe space for students to open up.',
    education: 'B.S. Psychology — University of Santo Tomas',
    yearsAtMmpns: 6,
    specialization: 'Behavioral Support & Peer Mediation',
    motto: 'Kindness is the best intervention.',
  },

  // ─── NON-TEACHING STAFF: REGISTRAR ───
  {
    id: 11,
    name: 'Gemma T. Lorenzo',
    role: 'School Registrar',
    department: 'Registrar',
    staffType: 'non-teaching',
    img: 'https://images.unsplash.com/photo-1623287073837-5b07d79739a3?auto=format&fit=crop&q=80&w=600',
    bio: 'Ms. Lorenzo is the guardian of academic records at MMPNS. With meticulous attention to detail, she manages enrollment, transcript requests, and official documentation. She has streamlined the registration process over the years, making it smoother for families each enrollment season.',
    education: 'B.S. Office Administration — Polytechnic University of the Philippines',
    yearsAtMmpns: 16,
    motto: 'Accuracy today preserves history for tomorrow.',
  },
  {
    id: 19,
    name: 'Raymond S. Garcia',
    role: 'Records & Enrollment Officer',
    department: 'Registrar',
    staffType: 'non-teaching',
    img: 'https://images.unsplash.com/photo-1752118464988-2914fb27d0f0?auto=format&fit=crop&q=80&w=600',
    bio: 'Raymond manages student enrollment processing and maintains the integrity of academic records in the school\'s database. He assists parents during enrollment season and handles transfer credentials. His calm and systematic approach ensures no document is ever misplaced or delayed.',
    education: 'B.S. Information Technology — Adamson University',
    yearsAtMmpns: 3,
    motto: 'Every record tells a student\'s story.',
  },
  {
    id: 20,
    name: 'Nilda C. Soriano',
    role: 'Administrative Clerk / Document Control',
    department: 'Registrar',
    staffType: 'non-teaching',
    img: 'https://images.unsplash.com/photo-1770922808877-1e41758b4f9d?auto=format&fit=crop&q=80&w=600',
    bio: 'Ms. Soriano handles day-to-day document processing in the registrar\'s office, from issuing certifications to managing Form 137 requests. She is often the first point of contact for parents needing records, and her efficiency and patience make the process stress-free for everyone.',
    education: 'B.S. Office Administration — National University',
    yearsAtMmpns: 7,
    motto: 'Organization is a form of respect.',
  },

  // ─── NON-TEACHING STAFF: LIBRARY ───
  {
    id: 12,
    name: 'Patricia M. Gonzales',
    role: 'Head Librarian',
    department: 'Library',
    staffType: 'non-teaching',
    img: 'https://images.unsplash.com/photo-1625667358548-3da433118055?auto=format&fit=crop&q=80&w=600',
    bio: 'Ms. Gonzales has transformed the MMPNS library into a vibrant learning hub. She curates the collection, runs reading programs, and has introduced a digital catalog system. Students love her "Book of the Month" recommendations and the cozy reading nooks she designed.',
    education: 'B.S. Library & Information Science — University of the Philippines Diliman',
    yearsAtMmpns: 10,
    motto: 'A library is a garden where ideas bloom.',
  },
  {
    id: 21,
    name: 'Arnel F. Dizon',
    role: 'Library Assistant / Media Coordinator',
    department: 'Library',
    staffType: 'non-teaching',
    img: 'https://images.unsplash.com/photo-1556360853-5c1e1b64ff6a?auto=format&fit=crop&q=80&w=600',
    bio: 'Arnel assists with daily library operations and manages the audiovisual equipment used across classrooms. He maintains the digital catalog, processes book check-outs, and helps students with research. He is also the go-to person for any tech-related issues in the library\'s computer section.',
    education: 'B.S. Library & Information Science — Polytechnic University of the Philippines',
    yearsAtMmpns: 4,
    motto: 'Knowledge should be accessible to all.',
  },
  {
    id: 22,
    name: 'Jennylyn R. Alcantara',
    role: 'Reading Program Facilitator',
    department: 'Library',
    staffType: 'non-teaching',
    img: 'https://images.unsplash.com/photo-1609126385558-bc3fc5082b0a?auto=format&fit=crop&q=80&w=600',
    bio: 'Ms. Alcantara runs the school\'s reading enrichment programs, including the popular "Read-a-Thon" and storytelling sessions for elementary students. She collaborates with English teachers to support struggling readers and curates age-appropriate book lists each quarter.',
    education: 'B.E.Ed., Major in English — Philippine Normal University',
    yearsAtMmpns: 3,
    motto: 'One story can change a child\'s world.',
  },

  // ─── NON-TEACHING STAFF: CLINIC ───
  {
    id: 13,
    name: 'Maricar A. Tolentino',
    role: 'School Nurse',
    department: 'Clinic',
    staffType: 'non-teaching',
    img: 'https://images.unsplash.com/photo-1765248149943-295c00f028d6?auto=format&fit=crop&q=80&w=600',
    bio: 'Nurse Maricar is the campus caregiver everyone trusts. From first aid to health education, she keeps the MMPNS community safe and informed. She coordinates annual medical check-ups, vaccination drives, and nutrition programs that ensure every child is healthy and ready to learn.',
    education: 'B.S. Nursing — University of Santo Tomas',
    yearsAtMmpns: 5,
    motto: 'A healthy child is a happy learner.',
  },
  {
    id: 23,
    name: 'Dr. Ernesto L. Villarama',
    role: 'School Physician (Part-time)',
    department: 'Clinic',
    staffType: 'non-teaching',
    img: 'https://images.unsplash.com/photo-1612638059828-c93f8882d376?auto=format&fit=crop&q=80&w=600',
    bio: 'Dr. Villarama visits MMPNS twice a week to conduct medical consultations and oversee the school health program. He reviews medical clearances, advises on health policies, and provides referrals when students need specialized care. Parents trust his calm, thorough approach to student health.',
    education: 'M.D. — University of the Philippines College of Medicine',
    yearsAtMmpns: 8,
    motto: 'Prevention is the best medicine.',
  },
  {
    id: 24,
    name: 'Angelica P. Navarro',
    role: 'Clinic Aide / First Aid Responder',
    department: 'Clinic',
    staffType: 'non-teaching',
    img: 'https://images.unsplash.com/photo-1770922808877-1e41758b4f9d?auto=format&fit=crop&q=80&w=600',
    bio: 'Ate Angel, as the students call her, is always ready with a kind smile and a cold compress. She manages the clinic when the nurse and doctor are off-campus, maintains the first aid inventory, and keeps detailed health logs. She is often the first responder to playground injuries and ensures students feel safe and cared for.',
    education: 'Caregiver NC II / First Aid & BLS Certified — TESDA',
    yearsAtMmpns: 2,
    motto: 'A bandage heals the wound, but care heals the heart.',
  },

  // ─── NON-TEACHING STAFF: MAINTENANCE & SECURITY ───
  {
    id: 14,
    name: 'Eduardo S. Ramos',
    role: 'Head of Security',
    department: 'Maintenance & Security',
    staffType: 'non-teaching',
    img: 'https://images.unsplash.com/photo-1652148555073-4b1d2ecd664c?auto=format&fit=crop&q=80&w=600',
    bio: 'Kuya Eddie, as everyone knows him, has been the vigilant guardian of MMPNS for over two decades. He knows every student by name, greets them each morning with a warm smile, and ensures the campus is safe from gate-open to gate-close. His dedication is the unsung backbone of the school.',
    education: 'Security Management Training — National Police Commission',
    yearsAtMmpns: 22,
    motto: 'Safety is not a duty — it is a promise to every family.',
  },
  {
    id: 25,
    name: 'Renato G. Magno',
    role: 'Maintenance Supervisor',
    department: 'Maintenance & Security',
    staffType: 'non-teaching',
    img: 'https://images.unsplash.com/photo-1690356107685-3725367f6f3f?auto=format&fit=crop&q=80&w=600',
    bio: 'Mang Rene keeps the MMPNS campus in top shape. From plumbing repairs to electrical fixes, he handles it all with skill and speed. He coordinates with outside contractors for larger projects and takes pride in ensuring every classroom is clean, safe, and ready for learning each morning.',
    education: 'Electrical Installation & Maintenance NC II — TESDA',
    yearsAtMmpns: 15,
    motto: 'A well-kept school is a well-loved school.',
  },
  {
    id: 26,
    name: 'Joel M. Panganiban',
    role: 'Utility & Groundskeeper',
    department: 'Maintenance & Security',
    staffType: 'non-teaching',
    img: 'https://images.unsplash.com/photo-1604118600242-e7a6d23ec3a9?auto=format&fit=crop&q=80&w=600',
    bio: 'Kuya Joel is the quiet hero who ensures the campus grounds are always presentable. He maintains the school garden, handles waste management, and assists with event setups. Rain or shine, he arrives before anyone else to make sure MMPNS is ready to welcome students each day.',
    education: 'High School Diploma / Various TESDA Short Courses',
    yearsAtMmpns: 10,
    motto: 'Hard work speaks louder than words.',
  },
];