import jamesCaraanImg from '../../../assets/no_image.png';
import jamesCaraanVintageImg from '../../../assets/no_image.png';
import { AlumniProfile } from './types';

export const alumniProfiles: AlumniProfile[] = [
  {
    id: 1,
    name: 'James Caraan',
    batch: '1993',
    role: 'Actor & Executive Producer',
    field: 'Arts & Media',
    img: jamesCaraanImg,
    vintageImg: jamesCaraanVintageImg,
    quote: 'Everything I am on stage and on screen started with the confidence I found in the hallways of MMPNS.',
    story: 'James Caraan is a multi-talented Filipino actor, comedian, and executive producer who has made a significant mark in Philippine entertainment. A proud elementary alumnus of Madre Maria Pia Notari School (Batch 1993), James discovered his love for performance during school programs and Christmas plays at MMPNS. That early spark of creativity eventually grew into a career spanning film, television, and live comedy. He is known for his work in Sampung Utos Kay Josh, Unli Life, Mighty Robo V, P.O.V. (Pepe On Vlog), The KoolPals Comedy Special, Jhon en Martian, and Rainbow Rumble. As an executive producer, James has championed original Filipino stories, helping bring independent films and comedy specials to wider audiences. His comedic timing, infectious energy, and genuine heart have earned him a loyal following and the respect of peers in the industry.',
    favoriteMemory: 'Performing in the school Christmas program in front of all the parents and teachers. I remember being so nervous, but the moment I heard the crowd laugh at my lines, I knew — this is what I was meant to do. That MMPNS stage was my very first stage.',
    messageToMMPNS: 'To the kids at MMPNS now: don\'t be afraid to be the funny one, the loud one, the different one. The things that make you stand out in school are the same things that will make you shine in life. MMPNS gave me a safe place to be myself — and that\'s the greatest gift any school can give.',
  },
  {
    id: 2,
    name: 'Engr. John Reyes',
    batch: '2010',
    role: 'Project Manager, Megaworld Corporation',
    field: 'Engineering',
    img: 'https://images.unsplash.com/photo-1605504836193-e77d3d9ede8a?auto=format&fit=crop&q=80&w=800',
    quote: 'The discipline I learned at MMPNS became the foundation of every project I lead.',
    story: 'John was known as the quiet achiever in his batch. While others were louder, he let his work speak for itself—a trait he credits to the humility he learned at MMPNS. After graduating with honors, he pursued Civil Engineering at DLSU and quickly rose through the ranks at Megaworld. He has managed the construction of several landmark buildings across the Philippines.',
    favoriteMemory: 'Science Week experiments and our teacher Mrs. Dela Cruz making chemistry feel like magic. That spark of curiosity never left me.',
    messageToMMPNS: 'Build strong foundations—not just in academics, but in character. That\'s what MMPNS gave me, and it\'s what I carry every single day.',
  },
  {
    id: 3,
    name: 'Atty. Clara Cruz',
    batch: '2008',
    role: 'Human Rights Advocate, CHR Philippines',
    field: 'Law',
    img: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=800',
    quote: 'Justice was a word I first truly understood through the Gospel values taught at MMPNS.',
    story: 'Clara was the fierce debater of Batch 2008 who always stood up for what was right. That fire led her to the UP College of Law, where she became an active member of the legal aid society. Now an attorney at the Commission on Human Rights, she fights for the marginalized and underrepresented—a calling she traces back to the school\'s emphasis on social responsibility.',
    favoriteMemory: 'The annual Recollection Day in 4th year. We were asked to write letters to our future selves. I still have mine—and I\'ve become exactly who I promised I would be.',
    messageToMMPNS: 'Never be afraid to speak truth. The courage you learn in those classrooms will serve you in courtrooms, boardrooms, and everywhere in between.',
  },
  {
    id: 4,
    name: 'Ms. Patricia Lim',
    batch: '2012',
    role: 'Head Nurse, St. Luke\'s Medical Center',
    field: 'Healthcare',
    img: 'https://images.unsplash.com/photo-1718006915613-bcb972cabdb1?auto=format&fit=crop&q=80&w=800',
    quote: 'Caring for others was always the MMPNS way. I just made it my profession.',
    story: 'Patricia\'s classmates remember her as the one who always had band-aids in her bag and a comforting word for anyone in tears. That innate compassion blossomed into a nursing career at St. Luke\'s, where she now leads a team of nurses in the ICU. She has also volunteered in medical missions across Visayas, channeling the spirit of service she first learned at MMPNS.',
    favoriteMemory: 'Our class performing "The Sound of Music" for the school festival. I was just in the chorus, but the teamwork and joy we shared backstage—that was everything.',
    messageToMMPNS: 'Be kind. It costs nothing, but it means everything to someone going through a hard time.',
  },
  {
    id: 5,
    name: 'Mr. Gabriel Torres',
    batch: '2003',
    role: 'Creative Director, BBDO Guerrero',
    field: 'Arts & Media',
    img: 'https://images.unsplash.com/photo-1552358155-515e264cb8b8?auto=format&fit=crop&q=80&w=800',
    quote: 'My first art exhibit was in the MMPNS hallway. Look where those walls led me.',
    story: 'Gabriel was the student who doodled in the margins of his notebooks—and his teachers wisely nurtured that creativity instead of stifling it. He went on to study Fine Arts at UST and eventually became one of the youngest creative directors at BBDO Guerrero, one of the Philippines\' top advertising agencies. His campaigns have won multiple Cannes Lions and Araw Awards.',
    favoriteMemory: 'Painting murals on the school walls for Buwan ng Wika. Seeing my artwork displayed where everyone walked past every day—that was my first taste of what public art could mean.',
    messageToMMPNS: 'Your talent is a gift from God. Don\'t hide it. Polish it, share it, and use it to uplift others.',
  },
  {
    id: 6,
    name: 'Ms. Angela Villanueva',
    batch: '2015',
    role: 'Research Scientist, DOST-ASTI',
    field: 'Science',
    img: 'https://images.unsplash.com/photo-1618053448748-b7251851d014?auto=format&fit=crop&q=80&w=800',
    quote: 'MMPNS gave me roots in faith and wings in science.',
    story: 'Angela represented MMPNS in multiple science fairs during her junior high years, winning regional awards that fueled her passion for discovery. She earned a full scholarship to UP Diliman for Physics and later completed her Master\'s at the National Institute of Physics. Now at DOST-ASTI, she works on satellite technology and disaster preparedness systems for the Philippines.',
    favoriteMemory: 'The first time I won a science fair medal in Grade 6. My teacher cried, my parents cried, I cried. That moment showed me that effort and curiosity are always rewarded.',
    messageToMMPNS: 'Never stop asking "why." That curiosity is the most precious thing MMPNS can nurture in you.',
  },
  {
    id: 7,
    name: 'Mr. Rafael Mendoza',
    batch: '2007',
    role: 'Founder & CEO, Harana Social Enterprise',
    field: 'Entrepreneurship',
    img: 'https://images.unsplash.com/photo-1648448942225-7aa06c7e8f79?auto=format&fit=crop&q=80&w=800',
    quote: 'Business is about people, not profit. MMPNS taught me that before any MBA could.',
    story: 'Rafael was the student council president who organized fundraisers for typhoon victims and led the Christmas outreach program for three consecutive years. That social consciousness carried into his career. After working in corporate banking, he founded Harana, a social enterprise that provides livelihood opportunities for marginalized communities. His company has empowered over 500 families across Luzon.',
    favoriteMemory: 'Leading the Christmas gift-giving outreach in Smokey Mountain. Seeing children smile because of something our school community did together—that changed my life forever.',
    messageToMMPNS: 'The world doesn\'t need more bosses. It needs more leaders with heart. Be that leader.',
  },
  {
    id: 8,
    name: 'Ms. Isabelle Tan',
    batch: '2014',
    role: 'Special Education Teacher, DepEd',
    field: 'Education',
    img: 'https://images.unsplash.com/photo-1551402991-6e4b5fc0b01c?auto=format&fit=crop&q=80&w=800',
    quote: 'My MMPNS teachers taught me that every child deserves patience and love.',
    story: 'Isabelle always had a soft spot for the classmates who struggled. She\'d stay after class to help them review, a habit her teachers at MMPNS lovingly encouraged. She pursued Special Education at PNU and now teaches children with learning disabilities in a public school in Parañaque. Her inclusive teaching methods have been recognized by DepEd as a model program.',
    favoriteMemory: 'The way our teachers would greet us by name every morning at the gate. Such a small thing, but it made you feel like you belonged. I do the same with my students now.',
    messageToMMPNS: 'You are more than your grades. Your kindness, your patience, your faith—those are your real report card.',
  },
  {
    id: 9,
    name: 'Mr. Marco Aguilar',
    batch: '2011',
    role: 'Senior Auditor, SGV & Co.',
    field: 'Finance',
    img: 'https://images.unsplash.com/photo-1649186019834-18ee06d7d5ad?auto=format&fit=crop&q=80&w=800',
    quote: 'Integrity isn\'t just a word in accounting. It was a way of life at MMPNS.',
    story: 'Marco was the math whiz of Batch 2011 who could solve problems faster than the calculator. His analytical mind led him to BSA at De La Salle University, where he graduated Cum Laude. Now a senior auditor at one of the Big Four, he handles multi-billion peso accounts with the same meticulousness and integrity he learned from his formative years at MMPNS.',
    favoriteMemory: 'Math Olympics preparation with Sir Mendez. We\'d stay until 5PM practicing problem sets, fueled by pandesal from the school canteen. Those afternoons taught me discipline.',
    messageToMMPNS: 'Hard work compounds like interest. Start building your discipline now and it will pay dividends for the rest of your life.',
  },
  {
    id: 10,
    name: 'Ms. Sophia Reyes',
    batch: '2016',
    role: 'Community Development Officer, GK Enchanted Farm',
    field: 'Social Work',
    img: 'https://images.unsplash.com/photo-1758599668178-d9716bbda9d5?auto=format&fit=crop&q=80&w=800',
    quote: 'Service was never just a subject at MMPNS—it was embedded in everything we did.',
    story: 'Sophia is the embodiment of Madre Maria Pia\'s spirit of selfless service. During her time at MMPNS, she was always the first to volunteer—whether for school cleanups, outreach programs, or parish activities. She studied Community Development at UP Manila and now works with Gawad Kalinga, building sustainable communities for the poorest families in Bulacan.',
    favoriteMemory: 'Our batch\'s tree-planting activity in La Mesa Watershed. We planted 200 seedlings, and knowing those trees are growing right now fills me with so much pride.',
    messageToMMPNS: 'The world is big and it needs you. Don\'t wait until you\'re "ready"—start serving now, right where you are.',
  },
];